# coding: utf-8
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道', alias_name: 'hoge'},
    {id: 2, name: '青森県', alias_name: 'hoge'},
    {id: 3, name: '岩手県', alias_name: 'hoge'},
    {id: 4, name: '宮城県', alias_name: 'hoge'},
    {id: 5, name: '秋田県', alias_name: 'hoge'},
    {id: 6, name: '山形県', alias_name: 'hoge'},
    {id: 7, name: '福島県', alias_name: 'hoge'},
    {id: 8, name: '茨城県', alias_name: 'hoge'},
    {id: 9, name: '栃木県', alias_name: 'hoge'},
    {id: 10, name: '群馬県', alias_name: 'hoge'},
    {id: 11, name: '埼玉県', alias_name: 'hoge'},
    {id: 12, name: '千葉県', alias_name: 'hoge'},
    {id: 13, name: '東京都', alias_name: 'hoge'},
    {id: 14, name: '神奈川県', alias_name: 'hoge'},
    {id: 15, name: '新潟県', alias_name: 'hoge'},
    {id: 16, name: '富山県', alias_name: 'hoge'},
    {id: 17, name: '石川県', alias_name: 'hoge'},
    {id: 18, name: '福井県', alias_name: 'hoge'},
    {id: 19, name: '山梨県', alias_name: 'hoge'},
    {id: 20, name: '長野県', alias_name: 'hoge'},
    {id: 21, name: '岐阜県', alias_name: 'hoge'},
    {id: 22, name: '静岡県', alias_name: 'hoge'},
    {id: 23, name: '愛知県', alias_name: 'hoge'},
    {id: 24, name: '三重県', alias_name: 'hoge'},
    {id: 25, name: '滋賀県', alias_name: 'hoge'},
    {id: 26, name: '京都府', alias_name: 'hoge'},
    {id: 27, name: '大阪府', alias_name: 'hoge'},
    {id: 28, name: '兵庫県', alias_name: 'hoge'},
    {id: 29, name: '奈良県', alias_name: 'hoge'},
    {id: 30, name: '和歌山県', alias_name: 'hoge'},
    {id: 31, name: '鳥取県', alias_name: 'hoge'},
    {id: 32, name: '島根県', alias_name: 'hoge'},
    {id: 33, name: '岡山県', alias_name: 'hoge'},
    {id: 34, name: '広島県', alias_name: 'hoge'},
    {id: 35, name: '山口県', alias_name: 'hoge'},
    {id: 36, name: '徳島県', alias_name: 'hoge'},
    {id: 37, name: '香川県', alias_name: 'hoge'},
    {id: 38, name: '愛媛県', alias_name: 'hoge'},
    {id: 39, name: '高知県', alias_name: 'hoge'},
    {id: 40, name: '福岡県', alias_name: 'hoge'},
    {id: 41, name: '佐賀県', alias_name: 'hoge'},
    {id: 42, name: '長崎県', alias_name: 'hoge'},
    {id: 43, name: '熊本県', alias_name: 'hoge'},
    {id: 44, name: '大分県', alias_name: 'hoge'},
    {id: 45, name: '宮崎県', alias_name: 'hoge'},
    {id: 46, name: '鹿児島県', alias_name: 'hoge'},
    {id: 47, name: '沖縄県', alias_name: 'hoge'}
  ]
end